\c private_clinic_db

CREATE TABLE IF NOT EXISTS diagnoses (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(7) NOT NULL
);

CREATE TABLE IF NOT EXISTS specialities (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS patient_categories (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR NOT NULL,
        discount_percentage INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS services (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR NOT NULL,
        price INTEGER NOT NULL,
        available BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        last_name VARCHAR(50) NOT NULL,
        first_name VARCHAR(50) NOT NULL,
        middle_name VARCHAR(50),
        hashed_password VARCHAR
);

CREATE TABLE IF NOT EXISTS doctors (
        user_id INTEGER NOT NULL PRIMARY KEY,
        experience INTEGER NOT NULL,
        quit_clinic BOOLEAN NOT NULL,
        speciality_id INTEGER NOT NULL,
        category_id INTEGER NOT NULL,
        FOREIGN KEY(user_id) REFERENCES users (id),
        FOREIGN KEY(speciality_id) REFERENCES specialities (id),
        FOREIGN KEY(category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS patients (
        user_id INTEGER NOT NULL PRIMARY KEY,
        birthday DATE NOT NULL,
        category_id INTEGER,
        FOREIGN KEY(user_id) REFERENCES users (id),
        FOREIGN KEY(category_id) REFERENCES patient_categories (id)
);

CREATE TABLE IF NOT EXISTS visiting_sessions (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        patient_id INTEGER,
        FOREIGN KEY(patient_id) REFERENCES patients (user_id) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS visits (
        id INTEGER NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        visiting_session_id INTEGER NOT NULL,
        doctor_id INTEGER NOT NULL,
        service_id INTEGER NOT NULL,
        diagnosis_id INTEGER,
        appointment_datetime DATE NOT NULL,
        discounted_price INTEGER NOT NULL,
        anamnesis VARCHAR,
        opinion VARCHAR,
        FOREIGN KEY(visiting_session_id) REFERENCES visiting_sessions (id) ON DELETE SET NULL ON UPDATE CASCADE,
        FOREIGN KEY(doctor_id) REFERENCES doctors (user_id) ON DELETE SET NULL ON UPDATE CASCADE,
        FOREIGN KEY(service_id) REFERENCES services (id) ON DELETE RESTRICT ON UPDATE CASCADE,
        FOREIGN KEY(diagnosis_id) REFERENCES diagnoses (id) ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO categories (name) VALUES ('second'), ('first'), ('highest');

INSERT INTO diagnoses (name)
VALUES
('Старческая катаракта'),
('Афакия'),
('Вывих хрусталика'),
('Болезнь хрусталика неуточненная'),
('Глаукома'),
('Слепота и пониженное зрение'),
('Расстройства зрения'),
('Отслойка и разрывы сетчатки'),
('Конъюнктивит'),
('Паралитическое косоглазие'),
('Нарушение содружественного движения глаз неуточненное'),
('Миопия'),
('Астигматизм'),
('Нарушения аккомодации'),
('Другие нарушения рефракции');

INSERT INTO specialities (name) VALUES ('Офтальмолог'), ('Хирург-офтальмолог'), ('Оптометрист');

INSERT INTO services (name, price, available)
VALUES
('Диагностика зрения', 800, TRUE),
('Хирургия катаракты', 8000, TRUE),
('Лазерная коррекция зрения', 25000, TRUE),
('Определение глюкозы в сыворотке крови', 1500, TRUE),
('Тонометрия глаза бесконтактная', 500, FALSE);

INSERT INTO patient_categories (name, discount_percentage)
VALUES
('Постоянный клиент', 5),
('Категория 1', 6),
('Категория 2', 12),
('Категория 3', 18);

INSERT INTO users (last_name, first_name, middle_name, hashed_password)
VALUES
('Кукушкина', 'Мадина', 'Александровна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Королева', 'Арина', 'Дмитриевна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Зайцева', 'Арина', 'Тихоновна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Иванова', 'Екатерина', 'Андреевна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Беляев', 'Марк', 'Ярославович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Смирнова', 'Василиса', 'Глебовна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Котов', 'Лев', 'Даниилович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Козлова', 'Василиса', 'Артёмовна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Ильин', 'Максим', 'Александрович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Волков', 'Николай', 'Тимофеевич', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Давыдов', 'Денис', 'Иванович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Сальников', 'Владислав', 'Родионович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Мельникова', 'Таисия', 'Егоровна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Баранов', 'Андрей', 'Максимович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Зайцев', 'Дмитрий', 'Иванович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Макарова', 'Валерия', 'Александровна', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC'),
('Сорокин', 'Александр', 'Максимович', '$2y$10$R2xOC21i0MRovHXvuGd18.M4OLhbZ5JC/KT3SvOJ.K1itFJJPv/TC');

INSERT INTO doctors (user_id, experience, quit_clinic, speciality_id, category_id)
VALUES
(1, 10, FALSE, 1, 1),
(2, 10, TRUE, 1, 1),
(3, 4, FALSE, 1, 1),
(4, 20, FALSE, 1, 1),
(5, 15, FALSE, 1, 1);

INSERT INTO patients (user_id, birthday, category_id)
VALUES
(6, '1998-07-19', 2),
(7, '1990-10-20', 1),
(8, '1993-12-10', NULL),
(9, '1984-12-10', NULL),
(10, '1984-12-10', 2),
(11, '2000-06-15', 1),
(12, '2000-06-17', 1),
(13, '2000-06-09', 1),
(14, '2001-06-19', 1),
(15, '2001-06-19', 1),
(16, '2004-07-19', 1),
(17, '1998-07-19', NULL);
