"""add hashed_password field in doctors table

Revision ID: e21b3e105b0e
Revises: 644d8b1b5ad7
Create Date: 2024-06-19 19:06:43.971327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e21b3e105b0e'
down_revision: Union[str, None] = '644d8b1b5ad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'hashed_password')
    # ### end Alembic commands ###
